### ISSUE TITLE
SimpleCRUD is not netcoreapp1.0 compatible

### ISSUE THREAD

**Issue by richardtallent** [ericdc1/Dapper.SimpleCRUD#101]
Please add support for .NET Core. I'm developing a personal ASP.NET Core project under OS X using PostgreSQL, Dapper itself is running like a champ, so I'm hoping this would require not much more than a build config change.

**Comment by brayannluiz** [comment]
I'm facing the same situation here.

**Comment by xalikoutis** [comment]
I added support to .Net Core, it is working, but i missing tests. The easy way is to create a new test project only for .Net core. The hard way is to change the namespace to Dapper.SimpleCRUD.Core, explicitly declare types and use some compiler directives in order to have a common code base.

But i think it is time to drop projects that target .net4 and go for .net standard 1.3 which can be referenced to any project targeting .net4.6 and above

**Comment by brayannluiz** [comment]
I appreciate your efforts @xalikoutis.

**Comment by ericdc1** [comment]
This is great. I will review this. I am ok with having a separate project for the .net core tests. I would rather be able to delete the old 4.0 and 4.6 code when .net core is what everyone is using than try to untangle a bunch of compiler directives. 

If you wouldn't mind, I would love to know what you had to do to make it work. I tried reading to understand what needed done to support Core but just got lost in this https://oren.codes/2015/06/09/pcls-net-core-dnx-and-uwp/ and https://blogs.msdn.microsoft.com/dotnet/2016/02/10/porting-to-net-core/

**Comment by xalikoutis** [comment]
So i adopted the way Dapper targets different frameworks 4,4.5,core through a single .net core project. I added compile directives and everything builds successfully. I did some manual tests and nothing seems to be broken.  Next i ll create a new test .net core project for including all the frameworks.

https://github.com/xalikoutis/Dapper.SimpleCRUD/tree/master/Dapper.SimpleCRUD%20NetCore

**Comment by ericdc1** [comment]
working on it
