### ISSUE TITLE
GetList with WHERE behaving like LIKE instead of =

### ISSUE THREAD

**Issue by ccrookston** [ericdc1/Dapper.SimpleCRUD#147]
I have this method:

        public static IEnumerable<T> GetList(string where, Dictionary<string, object> parameters)
        {
            IEnumerable<T> entities;
            using (var connection = OpenConnection())
            {
                entities = connection.GetList<T>(where, new DynamicParameters(parameters));
            }
            return entities;
        }

And I call it like such:

```
    string publicID = "463EC1EE-8AAB-4ABA-9B39-132BC8D3236E"
    Dictionary<string, object> parameters = new Dictionary<string, object>();
    parameters.Add("@APIPublicID", publicID);
    var apiUsers = Repository<APIUsers>.GetList("WHERE APIPublicID = @APIPublicID", parameters).ToList();
```

That works beautifully.  But here's the really weird thing. If I add some extra letters or numbers on the end of the guid `publicID `, it STILL works:

Instead of:

    string publicID = "463EC1EE-8AAB-4ABA-9B39-132BC8D3236E"

I do...

    string publicID = "463EC1EE-8AAB-4ABA-9B39-132BC8D3236EABCDEFG"
    .... // rest of the method as before

I get the exact same results. If I make the guid shorter, or if I change characters inside of it, then it behaves as expected.  

Am I doing something wrong? Or is this a bug?

**Comment by ericdc1** [comment]
If anything the bug is with SQL Server. When querying a GUID column, SQL Server only takes the first 32 characters into account for some reason. 

If I run this query directly in SQL Server Management Studio you will see this. Here is a screenshot for you: https://www.screencast.com/t/9vQ6a8llXD 

I ran these 3 as a test 

` SELECT [Id] ,[Guid] FROM [dbo].[ReferralSources] where id = 3`

`SELECT [Id] ,[Guid] FROM [dbo].[ReferralSources] where GUID = '1BDB45C3-B632-40DC-A6B9-B7C41218658F'`

`SELECT [Id] ,[Guid] FROM [dbo].[ReferralSources] where GUID = '1BDB45C3-B632-40DC-A6B9-B7C41218658F99999'`

Here are the results:

Id          Guid
----------- ------------------------------------
3           1BDB45C3-B632-40DC-A6B9-B7C41218658F

(1 row(s) affected)

Id          Guid
----------- ------------------------------------
3           1BDB45C3-B632-40DC-A6B9-B7C41218658F

(1 row(s) affected)

Id          Guid
----------- ------------------------------------
3           1BDB45C3-B632-40DC-A6B9-B7C41218658F

(1 row(s) affected)
