### ISSUE TITLE
Method not found: '!!0 Dapper.SimpleCRUD.Insert(System.Data.IDbConnection, System.Object, System.Data.IDbTransaction, System.Nullable`1<Int32>)'. ''

### ISSUE THREAD

**Issue by senglory** [ericdc1/Dapper.SimpleCRUD#160]
Method not found: '!!0 Dapper.SimpleCRUD.Insert(System.Data.IDbConnection, System.Object, System.Data.IDbTransaction, System.Nullable`1<Int32>)'.: '!!0 Dapper.SimpleCRUD.Insert(System.Data.IDbConnection, System.Object, System.Data.IDbTransaction, System.Nullable`1<Int32>)'.

Got the latest Nuget package. What's wrong with my code?

**Comment by ericdc1** [comment]
Hard to say that that limited info. Check out the working tests and work from there: https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs

**Comment by MonasteryJohn** [comment]
I found this issue while dealing with a similar error message in my own project. Just figured I'd comment here in case someone else stumbled into this as well.

For me, the problem was mismatching versions of Dapper.SimpleCRUD in my solution. Using Nuget to consolidate the versions, fixed the issue.
