### ISSUE TITLE
Support IN Clauses for Selects...

### ISSUE THREAD

**Issue by coderabsolute** [ericdc1/Dapper.SimpleCRUD#67]
Possible to include the support of IN Clauses for Select statements? :)

**Comment by elmar-de-groot** [comment]
Hi, can you provide a bit more detail? 
You might also want to checkout this thread: http://stackoverflow.com/questions/8388093/select-from-x-where-id-in-with-dapper-orm

**Comment by coderabsolute** [comment]
Thanks for the link, I have seen that earlier.

I was thinking that SimpleCrud's GetList function would support the 'IN' Clause...

**Comment by ericdc1** [comment]
Closing this for now as complex where clauses are probably better served with good old Dapper and some SQL. Anything I would invent to try to supplant SQL would probably just be harder to use. 

SimpleCrud does support a where clause so you *could* generate the where yourself like this:

       connection.GetList<User>("where id in (1,2,3,4,5)");  

If you have any suggestions on how this could work otherwise without making it too complex let me know.
