### ISSUE TITLE
dotnetcore support?

### ISSUE THREAD

**Issue by BTXAndy** [ericdc1/Dapper.SimpleCRUD#94]
Hi,

I'm getting this error when trying to target NETStandard:

Dapper itself doesn't seem to have an issue with it. Is this something that can easily be fixed or worked around?

Package Dapper.SimpleCRUD 1.12.0 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Dapper.SimpleCRUD 1.12.0 supports:
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)

Thanks

**Comment by ericdc1** [comment]
Hello,
I have made no attempt to make this work with .Net Core as it changed drastically over the last 2 years. I will put it on my list of things to look into. In the meantime, I would be glad to consider a pull request assuming the PR only made it .Net Core compatible without also adding or changing existing functionality. 

Eric

**Comment by BTXAndy** [comment]
Hi Eric,

I don't have access to Visual Studio as I'm on Mac so unfortunately I can't follow the articles that have been posted on porting a library.

However, in case it helps, this tool might make the job rather straightforward:
https://github.com/onovotny/ReferenceGenerator

The author of the tool wrote this article: https://oren.codes/2016/06/23/portable-is-dead-long-live-netstandard/

Have a look. It analyses your dll and generates a nuspec file.

I'm more than happy to test.

Thanks

**Comment by ppranayy** [comment]
Please add the support for .net core

**Comment by joseazevedo** [comment]
ya...Please add the support for .net core.

Thanks for this great Library

**Comment by ericdc1** [comment]
This is in my longer term plan but since I don't need it myself right now and don't have a clear idea on how to accomplish it, this is going to take some time. If anyone has a good idea on what steps to take to do this please let me know. 

These links are what I have to go on so far:
http://www.michael-whelan.net/porting-dotnet-framework-library-to-dotnet-core/ 
https://blogs.msdn.microsoft.com/dotnet/2016/02/10/porting-to-net-core/
